## Concepts
- functions
- lambda
- numpy

In [1]:
def addone(a):
    print("hello")
    return a + 1

In [2]:
answer = addone(2)
answer

hello


3

In [5]:
def addone(a):
    # print(a)
    return a + 1, a+a

In [6]:
b = 1
addone(b)

(2, 2)

In [7]:
addone = lambda x: x+1

In [8]:
addone(3.5)

4.5

In [9]:
squaring = lambda x: x**2
squaring(5)

25

In [10]:
squaring = lambda x, y, z: (x+y,y+z,z+x) 
squaring(1,2,3)

(3, 5, 4)

## Numpy

In [11]:
import numpy as np

C:\ProgramData\Anaconda3\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
C:\ProgramData\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
C:\ProgramData\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  stacklevel=1)


In [12]:
a = [1,2,3]
b = [4, 5, 6]
a + b

[1, 2, 3, 4, 5, 6]

In [13]:
a = np.array(a)
b = np.array(b)
a + b

array([5, 7, 9])

In [14]:
# import numpy as np
# def euclidean_distance(x, y):
#     """
#     sqrt((x_1 - y_1)^2 + ... + (x_N - y_N)^2)
#     """
#     # assert len(x) == len(y), "dimension mismatch"
#     d = [a-b for a,b in zip(x,y)]
#     d = [np.square(e) for e in d]
#     return np.sqrt(sum(d))

In [15]:
def euclidean_distance(x, y):
    d = [c-d for c,d in zip(x,y)]
    d = [np.square(e) for e in d]
    return np.sqrt(sum(d))

In [17]:
x = [1, 2, 3]
y = [4, 5, 6]
euclidean_distance(x, y)

5.196152422706632

In [22]:
def euclidean_distance(x, y):
    """
    sqrt((x_1 - y_1)^2 + ... + (x_N - y_N)^2)
    """
    
    import pdb; pdb.set_trace()
    d = x - y
    d = np.square(d)
    return np.sqrt(d.sum())

In [24]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
euclidean_distance(x, y)

> <ipython-input-22-d30f1584b53d>(7)euclidean_distance()
      5 
      6     import pdb; pdb.set_trace()
----> 7     d = x - y
      8     d = np.square(d)
      9     return np.sqrt(d.sum())

ipdb> print(d)
*** NameError: name 'd' is not defined
ipdb> n
> <ipython-input-22-d30f1584b53d>(8)euclidean_distance()
      6     import pdb; pdb.set_trace()
      7     d = x - y
----> 8     d = np.square(d)
      9     return np.sqrt(d.sum())
     10     return

ipdb> print(d)
[-3 -3 -3]
ipdb> n
> <ipython-input-22-d30f1584b53d>(9)euclidean_distance()
      6     import pdb; pdb.set_trace()
      7     d = x - y
      8     d = np.square(d)
----> 9     return np.sqrt(d.sum())
     10     return

ipdb> print(d)
[9 9 9]
ipdb> print(d.sum())
27
ipdb> exit


BdbQuit: 

## Summary
- You can `import` prebuilt libraries.
- Functions start with `def` and end with `return`.
- `lambda` are short one liner functions.

## Other concepts
- `zip` <- super useful.