In [1]:
import numpy as np

C:\ProgramData\Anaconda3\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
C:\ProgramData\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
C:\ProgramData\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  stacklevel=1)


In [11]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype = np.float64)

In [12]:
x

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [13]:
print(type(x[0]))

<class 'numpy.float64'>


In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.ones(4)

array([1., 1., 1., 1.])

In [17]:
b = np.zeros_like(x)

In [18]:
b.shape

(10,)

In [19]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [20]:
np.arange(1,5)

array([1, 2, 3, 4])

In [21]:
np.arange(1,2,0.5)

array([1. , 1.5])

In [23]:
np.arange(5,2,-0.25)

array([5.  , 4.75, 4.5 , 4.25, 4.  , 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 ,
       2.25])

In [24]:
a = np.arange(0,11)
b = 2

In [25]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
b**a

array([   1,    2,    4,    8,   16,   32,   64,  128,  256,  512, 1024],
      dtype=int32)

In [27]:
c = np.ones(10)

In [28]:
c

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [30]:
c =3**c

In [32]:
c[9] = 1.5

In [33]:
c


array([3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 1.5])

In [34]:
c.shape

(10,)

In [36]:
c.shape[0]

10

In [43]:
x = np.array([1, 2, 3],dtype=np.float64)
d = x.shape[0]
print(x[d-1] - x[-1]) 

0.0


In [51]:
tong = 0
for a in x:
    tong+=a;
tong/= x.shape[0]
tong


2.0

In [47]:
for i in range(x.shape[0]):
    x[i]=tong

array([2., 2., 2.])

In [52]:
a = 0.7*np.arange(10)

In [53]:
a

array([0. , 0.7, 1.4, 2.1, 2.8, 3.5, 4.2, 4.9, 5.6, 6.3])

In [56]:
idx = [True, True, False,True, True, False,True, True, False,True]

In [59]:
idx = np.arange(1,5,2)

In [60]:
a[idx]

array([0.7, 2.1])

In [64]:
a[5:7]

array([3.5, 4.2])

In [65]:
a[[1,3,5]]=1

In [66]:
a

array([0. , 1. , 1.4, 1. , 2.8, 1. , 4.2, 4.9, 5.6, 6.3])

In [71]:
a[-3:] = np.array([9,9,9])

In [100]:
a=np.arange(10)


In [101]:
a[::2]

array([0, 2, 4, 6, 8])

In [102]:
a[::-2]

array([9, 7, 5, 3, 1])

In [123]:
n=4

In [124]:
x = np.arange(2,2-0.25*n,-0.25)
x

array([2.  , 1.75, 1.5 , 1.25])

In [125]:
x[::-2] = np.ones_like(x[::-2])*-1

In [126]:
x

array([ 2. , -1. ,  1.5, -1. ])

In [133]:
n=5

In [134]:
y= np.ones(n)*-1
y

array([-1., -1., -1., -1., -1.])

In [135]:
y[::2].shape[0]

3

In [136]:
y[::2] = np.arange(2,2-0.5*y[::2].shape[0],-0.5)

In [137]:
y

array([ 2. , -1. ,  1.5, -1. ,  1. ])

In [140]:
x = np.array([1, 2, 3])
a = 3 
print(x + a)
print(6/x)
3**x


[4 5 6]
[6. 3. 2.]


array([ 3,  9, 27], dtype=int32)

In [141]:
x = np.arange(10)

In [142]:
x


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [144]:
y = np.pi/2-x
y

array([ 1.57079633,  0.57079633, -0.42920367, -1.42920367, -2.42920367,
       -3.42920367, -4.42920367, -5.42920367, -6.42920367, -7.42920367])

In [145]:
z = np.cos(x) - np.sin(x)
z

array([ 1.        , -0.30116868, -1.32544426, -1.1311125 ,  0.10315887,
        1.24258646,  1.23958578,  0.09691566, -1.13485828, -1.32324875])

In [152]:
z.sum()

-1.5335856994868342

In [153]:
x.sum()

45

In [156]:
norm_1=0
for i in range(z.shape[0]):
    norm_1 += np.abs(z[i])
norm_1

8.89807924957581

In [168]:
sum_soft=0
for i in range(x.shape[0]):
    sum_soft += np.exp(x[i])
sum_soft

12818.308050524603

In [173]:
g = np.zeros_like(x,dtype=np.float64)
for i in range(x.shape[0]):
     g[i] = np.exp(x[i])/sum_soft
g

array([7.80134161e-05, 2.12062451e-04, 5.76445508e-04, 1.56694135e-03,
       4.25938820e-03, 1.15782175e-02, 3.14728583e-02, 8.55520989e-02,
       2.32554716e-01, 6.32149258e-01])

In [174]:
x = np.array([1,4,5])
y = np.ones_like(x)*2

In [178]:
tich_vh = np.sum(x*y)
tich_vh

20

In [179]:
x.dot(y)

20

In [180]:
np.dot(x,y)

20

In [181]:
norm2 = np.sqrt(np.dot(x,x))

In [182]:
norm2

6.48074069840786

In [183]:
np.sqrt(4)

2.0

In [185]:
g.argmax()+1

10

In [192]:
x = np.arange(10)
b = np.max(x)
sum_soft=0
for i in range(x.shape[0]):
    sum_soft += np.exp(x[i]-b)
sum_soft

1.5819048852379487

In [193]:
h = np.zeros_like(x,dtype=np.float64)

for i in range(x.shape[0]):
     h[i] = np.exp(x[i]-b)/sum_soft
h

array([7.80134161e-05, 2.12062451e-04, 5.76445508e-04, 1.56694135e-03,
       4.25938820e-03, 1.15782175e-02, 3.14728583e-02, 8.55520989e-02,
       2.32554716e-01, 6.32149258e-01])

In [194]:
h.sum()

1.0

In [195]:
A = np.array([[1, 2], [3, 4]])

In [196]:
A

array([[1, 2],
       [3, 4]])

In [198]:
B = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [199]:
B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [200]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [204]:
np.eye(4,k=-2)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [205]:
np.diag([1, 3, 4])

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

In [206]:
np.diag(np.diag([1, 3, 4,5]))

array([1, 3, 4, 5])

In [209]:
np.diag(B, k=2)

array([3])

In [213]:
n=4

In [214]:
np.diag(np.arange(1,n+1),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [215]:
B


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [216]:
B[0][0]

1

In [217]:
B[2][1]

8

In [218]:
B[2, 1]

8

In [220]:
B[0]

array([1, 2, 3])

In [221]:
B[0][:]

array([1, 2, 3])

In [222]:
B[0, :]

array([1, 2, 3])

In [223]:
B[:, 1]

array([2, 5, 8])

In [230]:
def myfunc(A):
    tong =0;
    for i in range(0, A.shape[1], 2):
        tong += np.sum(A[:,i])
    return tong

In [231]:
myfunc(B)

30

In [232]:
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [233]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [234]:
A[0, 2:]

array([3, 4])

In [235]:
A[1, range(0, A.shape[1], 2)]

array([5, 7])

In [236]:
A[[0, 2], -1]

array([ 4, 12])

In [237]:
A[[1, 2]][:, [0,3]]

array([[ 5,  8],
       [ 9, 12]])

In [239]:
A[np.arange(0,A.shape[0],2)][:, np.arange(0,A.shape[1],2)].sum()

24

In [241]:
A = np.array([[1, 2, 6, 4], [6, 6, 8, 8], [9, 12, 2, 1]])

In [242]:
sum = 0
for i in range(A.shape[0]):
    sum+=np.max(A[i])-np.min(A[i])
sum

18

In [243]:
A = np.array([[1, 3], [2, 5]])

In [248]:
np.sqrt(np.sum(A*A))

6.244997998398398

In [257]:
A = np.array([[1, 2, 3, 3], [5, 7, 7, 10], [9, 10, 11, 12]])

In [258]:
B = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [255]:
def dist_fro(A, B):
    C = A-B
    return np.sum(C*C)

In [259]:
dist_fro(A,B)

6

In [260]:
A

array([[ 1,  2,  3,  3],
       [ 5,  7,  7, 10],
       [ 9, 10, 11, 12]])

In [261]:
A.T 

array([[ 1,  5,  9],
       [ 2,  7, 10],
       [ 3,  7, 11],
       [ 3, 10, 12]])

In [262]:
np.transpose(A)

array([[ 1,  5,  9],
       [ 2,  7, 10],
       [ 3,  7, 11],
       [ 3, 10, 12]])

In [266]:
A.reshape(3, 2, 2)

array([[[ 1,  2],
        [ 3,  3]],

       [[ 5,  7],
        [ 7, 10]],

       [[ 9, 10],
        [11, 12]]])

In [267]:
np.reshape(A, (3, 1, 4))

array([[[ 1,  2,  3,  3]],

       [[ 5,  7,  7, 10]],

       [[ 9, 10, 11, 12]]])

In [269]:
np.reshape(A, 12)

array([ 1,  2,  3,  3,  5,  7,  7, 10,  9, 10, 11, 12])

In [273]:
A.reshape(12)

array([ 1,  2,  3,  3,  5,  7,  7, 10,  9, 10, 11, 12])

In [274]:
A.reshape(2,-1)  #-1 de Python tu tinh

array([[ 1,  2,  3,  3,  5,  7],
       [ 7, 10,  9, 10, 11, 12]])

In [1]:
np.reshape(np.arange(1,13),(3, 4)).T.reshape(3,4)

NameError: name 'np' is not defined