In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
from feature_extraction import Featurizer
pd.set_option('display.max_columns', None)

C:\ProgramData\Anaconda3\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
C:\ProgramData\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
C:\ProgramData\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  stacklevel=1)


In [3]:
train_df = pd.read_csv("./train.csv")    #import train dataset
test_df = pd.read_csv("./test.csv")      #import test dataset

drop_cols = ["Name", "Age", "Ticket", "Cabin", "Embarked", "PassengerId"]   #các cột cần xóa
featurizer = Featurizer(drop_cols)                                
train_df, val_df = featurizer.get_train_features(train_df)                  

C:\Users\Administrator\Desktop\Udemy_AI\04_classification\feature_extraction.py:20: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df["Sex"] = self.le.fit_transform(train_df["Sex"])
C:\Users\Administrator\Desktop\Udemy_AI\04_classification\feature_extraction.py:21: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  val_df["Sex"] = self.le.transform(val_df["Sex"])
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:3997: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice fr

In [4]:
train_df

Survived  Sex  SibSp  Parch      Fare    2    3
0           1    1      0      2   20.5250  0.0  1.0
1           0    0      4      2   31.2750  0.0  1.0
2           0    1      0      0   32.3208  0.0  0.0
3           0    1      0      0    7.7292  0.0  1.0
4           0    1      0      0    7.8958  0.0  1.0
..        ...  ...    ...    ...       ...  ...  ...
796         1    0      0      0    7.6500  0.0  1.0
797         0    1      0      0   31.0000  0.0  0.0
798         0    1      2      0   14.1083  0.0  1.0
799         1    0      1      2  120.0000  0.0  0.0
800         0    1      0      1   77.2875  0.0  0.0

[801 rows x 7 columns]

In [5]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [12]:
model = LogisticRegression()
model.fit(train_df.drop("Survived", axis=1), train_df["Survived"])
y_pred = model.predict(train_df.drop("Survived", axis=1))
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,

In [13]:
model.predict_proba(train_df.drop("Survived", axis=1))

array([[0.89190636, 0.10809364],
       [0.62887081, 0.37112919],
       [0.61664269, 0.38335731],
       ...,
       [0.92476686, 0.07523314],
       [0.11030787, 0.88969213],
       [0.58866173, 0.41133827]])

In [17]:
import numpy as np
prob = model.predict_proba(train_df.drop("Survived", axis=1))
print(prob.shape)
(prob[:,1] > 0.5).astype(np.int32)


(801, 2)


array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,

In [18]:
accuracy_score(train_df["Survived"].values, y_pred)

0.7952559300873908

In [19]:
(train_df["Survived"].values == y_pred).mean()

0.7952559300873908

In [21]:
y_pred = model.predict(val_df.drop("Survived", axis=1))
accuracy_score(val_df["Survived"].values.squeeze(), y_pred.squeeze())

0.8222222222222222

In [22]:
y_pred = model.predict(val_df.drop("Survived", axis=1))
accuracy_score(val_df["Survived"].values, y_pred)

0.8222222222222222

In [28]:
from typing import Callable, Dict, List, Tuple

class Model():
    def __init__(
        self, 
        y_col: str,
        model: Callable, 
        metrics:Dict[str, Tuple[str, Callable]]=accuracy_score,
                ) -> None:
        self.model = model
        self.metrics = metrics
        self.y_col = y_col
        
    def print_metric(self, 
                     metric:Callable, 
                     metric_name: str,
                     metric_y_type: str,
                     df:pd.DataFrame, 
                     data_type:str) -> None:
        y_class = self.model.predict(df.drop(self.y_col, axis=1))
        y_prob = self.model.predict_proba(df.drop(self.y_col, axis=1))
        if metric_y_type == "prob":
            y_pred= y_prob
        else:
            y_pred = y_class
        metric_val = metric(df[self.y_col].values.squeeze(), y_pred.squeeze())
        print(f"{data_type} {metric_name}: {metric_val:.4f}")
        
    def fit(self, train_df: pd.DataFrame, val_df: pd.DataFrame) -> None:
        self.model.fit(train_df.drop(self.y_col, axis=1), train_df[self.y_col])
        
        for name, (metric_y_type, metric) in self.metrics.items():
            self.print_metric(metric, name, metric_y_type, train_df, "Training")
            self.print_metric(metric, name, metric_y_type, val_df, "Validation")

In [29]:
metric_list = {"Accuracy": ("class", accuracy_score)}
print(metric_list)

{'Accuracy': ('class', <function accuracy_score at 0x000000001A23B510>)}


In [30]:
logistic = LogisticRegression()
model = Model("Survived", logistic, metric_list)
model.fit(train_df, val_df)

Training Accuracy: 0.7953
Validation Accuracy: 0.8222


In [31]:
from sklearn.ensemble import RandomForestClassifier

random_forest = RandomForestClassifier(n_estimators=50, max_depth=3)
model = Model("Survived", random_forest, metric_list)
model.fit(train_df, val_df)

Training Accuracy: 0.8240
Validation Accuracy: 0.8111


In [32]:
from sklearn.gaussian_process import GaussianProcessClassifier

gp = GaussianProcessClassifier()
model = Model("Survived", gp, metric_list)
model.fit(train_df, val_df)

Training Accuracy: 0.8764
Validation Accuracy: 0.7778


In [33]:
from sklearn import metrics

def auc(y, pred):
    fpr, tpr, _ = metrics.roc_curve(y, pred[:, 1])
    return metrics.auc(fpr, tpr)

In [34]:
metric_list["AUC"] = ("prob", auc)

In [35]:
for model_ in [logistic, random_forest, gp]:
    model = Model("Survived", model_, metric_list)
    model.fit(train_df, val_df)
    print("="*30)

Training Accuracy: 0.7953
Validation Accuracy: 0.8222
Training AUC: 0.8306
Validation AUC: 0.8840
Training Accuracy: 0.8015
Validation Accuracy: 0.7778
Training AUC: 0.8600
Validation AUC: 0.8822
Training Accuracy: 0.8764
Validation Accuracy: 0.7778
Training AUC: 0.8937
Validation AUC: 0.8228


In [36]:
train_df["Survived"].mean()

0.38202247191011235